Fix dependency bounds issue for usnistgov/metaschema#265
More details with the reason for this PR can be found in the build
mentioned below.

```sh
Error:  Rule 0: org.apache.maven.plugins.enforcer.RequireUpperBoundDeps failed with message:
Failed while enforcing RequireUpperBoundDeps. The error(s) are [
Require upper bound dependencies error for org.xmlresolver:xmlresolver:5.2.0 paths to dependency are:
+-gov.nist.secauto.metaschema:metaschema-schema-generator:1.0.0-M2-SNAPSHOT
  +-net.sf.saxon:Saxon-HE:12.4
    +-org.xmlresolver:xmlresolver:5.2.0 (managed) <-- org.xmlresolver:xmlresolver:5.2.2
and
+-gov.nist.secauto.metaschema:metaschema-schema-generator:1.0.0-M2-SNAPSHOT
  +-net.sf.saxon:Saxon-HE:12.4
    +-org.xmlresolver:xmlresolver:5.2.0:data (managed) <-- org.xmlresolver:xmlresolver:5.2.2:data
]
```

https://github.com/usnistgov/metaschema-java/actions/runs/7042748869/job/19167401850